spring:
  application:
    name: microsservicos-java-spring
server:
  port: 8080			
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
  endpoint:
    health:
      show-details: ALWAYS
greeting-service:
  greeting: "Hola"
  default-value: "Múndo"