spring:
  application:
    name: microsservicos-java-spring
  config:
    import: optional:configserver:http://localhost:8888/
  cloud:
    config:
      profile: it
server:
  port: 8080			
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
  endpoint:
    health:
      show-details: ALWAYS
#greeting-service:
#  greeting: "Olá"
#  default-value: "Mundo"